-- Criar tabela USUARIOS
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIOS]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[USUARIOS](
        [ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
        [LOGIN] [varchar](50) NOT NULL,
        [SENHA] [varchar](255) NOT NULL,
        [NOME] [varchar](100) NOT NULL,
        [EMAIL] [varchar](200) NULL,
        [ADMINISTRADOR] [bit] NOT NULL DEFAULT(0),
        [ATIVO] [bit] NOT NULL DEFAULT(1),
        [DATA_CRIACAO] [datetime] NULL,
        CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC),
        CONSTRAINT [IX_USUARIOS_LOGIN_UNIQUE] UNIQUE NONCLUSTERED ([LOGIN] ASC)
    )
END
GO

-- Criar tabela PERMISSOES
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PERMISSOES]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PERMISSOES](
        [ID_PERMISSAO] [int] IDENTITY(1,1) NOT NULL,
        [CONTROLLER] [varchar](100) NOT NULL,
        [ACAO] [varchar](100) NOT NULL,
        [DESCRICAO] [varchar](200) NULL,
        [ATIVO] [bit] NOT NULL DEFAULT(1),
        CONSTRAINT [PK_PERMISSOES] PRIMARY KEY CLUSTERED ([ID_PERMISSAO] ASC),
        CONSTRAINT [IX_PERMISSOES_CONTROLLER_ACAO_UNIQUE] UNIQUE NONCLUSTERED ([CONTROLLER] ASC, [ACAO] ASC)
    )
END
GO

-- Criar tabela USUARIO_PERMISSOES
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO_PERMISSOES]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[USUARIO_PERMISSOES](
        [ID_USUARIO_PERMISSAO] [int] IDENTITY(1,1) NOT NULL,
        [ID_USUARIO] [int] NOT NULL,
        [ID_PERMISSAO] [int] NOT NULL,
        [PODE_VISUALIZAR] [bit] NOT NULL DEFAULT(1),
        [PODE_INCLUIR] [bit] NOT NULL DEFAULT(0),
        [PODE_ALTERAR] [bit] NOT NULL DEFAULT(0),
        [PODE_EXCLUIR] [bit] NOT NULL DEFAULT(0),
        CONSTRAINT [PK_USUARIO_PERMISSOES] PRIMARY KEY CLUSTERED ([ID_USUARIO_PERMISSAO] ASC),
        CONSTRAINT [IX_USUARIO_PERMISSOES_UNIQUE] UNIQUE NONCLUSTERED ([ID_USUARIO] ASC, [ID_PERMISSAO] ASC),
        CONSTRAINT [FK_USUARIO_PERMISSOES_USUARIOS] FOREIGN KEY([ID_USUARIO]) REFERENCES [dbo].[USUARIOS] ([ID_USUARIO]) ON DELETE CASCADE,
        CONSTRAINT [FK_USUARIO_PERMISSOES_PERMISSOES] FOREIGN KEY([ID_PERMISSAO]) REFERENCES [dbo].[PERMISSOES] ([ID_PERMISSAO])
    )
END
GO



















